version: '3'
services:
  frontend:
    image: lehela/frontend_dev
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    image: lehela/frontend_tests
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]
